/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package parkingcontrol;



import java.io.File;
import java.util.ArrayList;


/**
 *
 * @author davip
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        this.db = new DataBaseManagement();
        subscriberList = db.selectFromSubscriber();
        veiculeList = db.selectFromVeicule();
        this.updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SaveLoadDialog = new javax.swing.JFileChooser();
        AddVeicDialog = new javax.swing.JDialog();
        AddVeicDialogLicense = new javax.swing.JTextField();
        AddVeicDialogManualTime = new javax.swing.JTextField();
        AddVeicDialogSubscriber = new javax.swing.JCheckBox();
        AddVeicDialogHasKey = new javax.swing.JCheckBox();
        AddVeicDialogConfirmButton = new javax.swing.JToggleButton();
        TextPlacaDoVeiculo = new javax.swing.JLabel();
        TextHorarioDeEntrada = new javax.swing.JLabel();
        AddVeicDialogIsMotorBike = new javax.swing.JCheckBox();
        AddSubDialog = new javax.swing.JDialog();
        AddSubDialogName = new javax.swing.JTextField();
        AddSubDialogLicense = new javax.swing.JTextField();
        AddSubDialogContact = new javax.swing.JTextField();
        AddSubDialogTextName = new javax.swing.JLabel();
        AddSubDialogTextLicense = new javax.swing.JLabel();
        AddSubDialogTextContact = new javax.swing.JLabel();
        AddSubDialogConfirmButton = new javax.swing.JButton();
        AddSubDialogCarModel = new javax.swing.JTextField();
        AddSubDialogTextCarModel = new javax.swing.JLabel();
        AddSubDialogTextDays = new javax.swing.JLabel();
        AddSubDialogBox1 = new javax.swing.JCheckBox();
        AddSubDialogBox2 = new javax.swing.JCheckBox();
        AddSubDialogBox3 = new javax.swing.JCheckBox();
        AddSubDialogBox4 = new javax.swing.JCheckBox();
        AddSubDialogBox5 = new javax.swing.JCheckBox();
        AddSubDialogBox6 = new javax.swing.JCheckBox();
        AddSubDialogIsMotorBike = new javax.swing.JCheckBox();
        SubscriberView = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        SubTable = new javax.swing.JTable();
        RemoveVeicDialog = new javax.swing.JDialog();
        RemoveVeicDialogConfirmButton = new javax.swing.JButton();
        RemoveVeicDialogComboBox = new javax.swing.JComboBox<>();
        RemoveVeicDialogTextField = new javax.swing.JTextField();
        RemoveVeicDialogLabel = new javax.swing.JLabel();
        RemoveSubDialog = new javax.swing.JDialog();
        RemoveSubDialogComboBox = new javax.swing.JComboBox<>();
        RemoveSubDialogConfirmButton = new javax.swing.JButton();
        EditVeicDialog = new javax.swing.JDialog();
        EditVeicDialogComboBox = new javax.swing.JComboBox<>();
        EditVeicDialogConfirmButton = new javax.swing.JButton();
        EditVeicDialogFieldLicense = new javax.swing.JTextField();
        EditVeicDialogFieldTimeIn = new javax.swing.JTextField();
        EditVeicDialogFieldTimeOut = new javax.swing.JTextField();
        EditVeicDialogTextLicense = new javax.swing.JLabel();
        EditVeicDialogTextTimeIn = new javax.swing.JLabel();
        EditVeicDialogTextTimeOut = new javax.swing.JLabel();
        EditVeicDialogCheckBoxSub = new javax.swing.JCheckBox();
        EditVeicDialogCheckBoxHasKey = new javax.swing.JCheckBox();
        EditVeicDialogCheckBoxMoto = new javax.swing.JCheckBox();
        EditSubDialog = new javax.swing.JDialog();
        EditSubDialogComboBox = new javax.swing.JComboBox<>();
        EditSubDialogFieldName = new javax.swing.JTextField();
        EditSubDialogFieldCarModel = new javax.swing.JTextField();
        EditSubDialogFieldSubDate = new javax.swing.JTextField();
        EditSubDialogFieldSubDeadLine = new javax.swing.JTextField();
        EditSubDialogFieldContact = new javax.swing.JTextField();
        EditSubDialogFieldLicense = new javax.swing.JTextField();
        EditSubDialogCheckBoxIsMensalist = new javax.swing.JCheckBox();
        EditSubDialogCheckBoxIsMoto = new javax.swing.JCheckBox();
        EditSubDialogCheckBoxQua = new javax.swing.JCheckBox();
        EditSubDialogCheckBoxQui = new javax.swing.JCheckBox();
        EditSubDialogCheckBoxSex = new javax.swing.JCheckBox();
        EditSubDialogCheckBoxPNT = new javax.swing.JCheckBox();
        EditSubDialogCheckBoxSeg = new javax.swing.JCheckBox();
        EditSubDialogCheckBoxTer = new javax.swing.JCheckBox();
        EditSubDialogConfirmButton = new javax.swing.JButton();
        EditSubDIalogLabelContact = new javax.swing.JLabel();
        EditSubDIalogLabelLicense = new javax.swing.JLabel();
        EditSubDIalogLabelName = new javax.swing.JLabel();
        EditSubDIalogLabelCarModel = new javax.swing.JLabel();
        EditSubDIalogLabelSubDate = new javax.swing.JLabel();
        EditSubDIalogLabelSubDeadLine = new javax.swing.JLabel();
        AddVeic = new javax.swing.JButton();
        ScrollPaneTable = new javax.swing.JScrollPane();
        mainTable = new javax.swing.JTable();
        AddSub = new javax.swing.JButton();
        DesktopPane = new javax.swing.JDesktopPane();
        RemoveSub = new javax.swing.JButton();
        RemoveVeic = new javax.swing.JButton();
        MenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menubarNew = new javax.swing.JMenuItem();
        menubarOpen = new javax.swing.JMenuItem();
        menubarSave = new javax.swing.JMenuItem();
        menubarNewWindow = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        EditMenuEditVeic = new javax.swing.JMenuItem();
        EditMenuEditSub = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        ViewMenuSubscriberView = new javax.swing.JMenuItem();

        SaveLoadDialog.setPreferredSize(new java.awt.Dimension(500, 300));

        AddVeicDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        AddVeicDialog.setTitle("Adicionar Veículo");
        AddVeicDialog.setAlwaysOnTop(true);
        AddVeicDialog.setIconImage(img.getImage());
        AddVeicDialog.setLocation(DesktopPane.location());
        AddVeicDialog.setMinimumSize(new java.awt.Dimension(400, 300));
        AddVeicDialog.setResizable(false);

        AddVeicDialogLicense.setName("Placa do Carro"); // NOI18N
        AddVeicDialogLicense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddVeicDialogLicenseActionPerformed(evt);
            }
        });

        AddVeicDialogManualTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddVeicDialogManualTimeActionPerformed(evt);
            }
        });

        AddVeicDialogSubscriber.setText("Mensalista");

        AddVeicDialogHasKey.setText("Chave do Carro");

        AddVeicDialogConfirmButton.setText("Adicionar");
        AddVeicDialogConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddVeicDialogConfirmButtonActionPerformed(evt);
            }
        });

        TextPlacaDoVeiculo.setText("Placa do Veículo");

        TextHorarioDeEntrada.setText("Horário de Entrada");
        TextHorarioDeEntrada.setToolTipText("");

        AddVeicDialogIsMotorBike.setText("Moto");

        javax.swing.GroupLayout AddVeicDialogLayout = new javax.swing.GroupLayout(AddVeicDialog.getContentPane());
        AddVeicDialog.getContentPane().setLayout(AddVeicDialogLayout);
        AddVeicDialogLayout.setHorizontalGroup(
            AddVeicDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddVeicDialogLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(AddVeicDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddVeicDialogIsMotorBike)
                    .addGroup(AddVeicDialogLayout.createSequentialGroup()
                        .addComponent(AddVeicDialogSubscriber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AddVeicDialogHasKey))
                    .addGroup(AddVeicDialogLayout.createSequentialGroup()
                        .addGroup(AddVeicDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddVeicDialogLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddVeicDialogManualTime, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AddVeicDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextPlacaDoVeiculo)
                            .addComponent(TextHorarioDeEntrada)
                            .addGroup(AddVeicDialogLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(AddVeicDialogConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AddVeicDialogLayout.setVerticalGroup(
            AddVeicDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddVeicDialogLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(AddVeicDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddVeicDialogLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextPlacaDoVeiculo))
                .addGap(18, 18, 18)
                .addGroup(AddVeicDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddVeicDialogManualTime, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextHorarioDeEntrada))
                .addGap(18, 18, 18)
                .addGroup(AddVeicDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddVeicDialogSubscriber)
                    .addComponent(AddVeicDialogHasKey))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddVeicDialogIsMotorBike)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(AddVeicDialogConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        AddSubDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        AddSubDialog.setTitle("Adicionar Mensalista");
        AddSubDialog.setAlwaysOnTop(true);
        AddSubDialog.setIconImage(img.getImage());
        AddSubDialog.setMinimumSize(new java.awt.Dimension(400, 439));
        AddSubDialog.setName("AddSubDialog"); // NOI18N

        AddSubDialogName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSubDialogNameActionPerformed(evt);
            }
        });

        AddSubDialogTextName.setText("Nome");

        AddSubDialogTextLicense.setText("Placa");

        AddSubDialogTextContact.setText("Contato");

        AddSubDialogConfirmButton.setText("Adicionar");
        AddSubDialogConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSubDialogConfirmButtonActionPerformed(evt);
            }
        });

        AddSubDialogCarModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSubDialogCarModelActionPerformed(evt);
            }
        });

        AddSubDialogTextCarModel.setText("Modelo do carro");

        AddSubDialogTextDays.setText("Dias");

        AddSubDialogBox1.setText("Segunda");

        AddSubDialogBox2.setText("Terça");

        AddSubDialogBox3.setText("Quarta");

        AddSubDialogBox4.setText("Quinta");

        AddSubDialogBox5.setText("Sexta");

        AddSubDialogBox6.setText("Per-Noite");

        AddSubDialogIsMotorBike.setText("Moto");

        javax.swing.GroupLayout AddSubDialogLayout = new javax.swing.GroupLayout(AddSubDialog.getContentPane());
        AddSubDialog.getContentPane().setLayout(AddSubDialogLayout);
        AddSubDialogLayout.setHorizontalGroup(
            AddSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddSubDialogLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(AddSubDialogTextDays)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(AddSubDialogLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(AddSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddSubDialogLayout.createSequentialGroup()
                        .addGroup(AddSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddSubDialogName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AddSubDialogLicense, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AddSubDialogContact, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AddSubDialogCarModel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(AddSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddSubDialogTextCarModel)
                            .addComponent(AddSubDialogTextContact)
                            .addComponent(AddSubDialogTextLicense)
                            .addComponent(AddSubDialogTextName))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(AddSubDialogLayout.createSequentialGroup()
                        .addGroup(AddSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddSubDialogBox3)
                            .addComponent(AddSubDialogBox1)
                            .addComponent(AddSubDialogBox5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AddSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddSubDialogBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AddSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(AddSubDialogBox2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AddSubDialogBox4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                        .addGroup(AddSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddSubDialogConfirmButton)
                            .addComponent(AddSubDialogIsMotorBike))
                        .addGap(31, 31, 31))))
        );
        AddSubDialogLayout.setVerticalGroup(
            AddSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddSubDialogLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(AddSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddSubDialogName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddSubDialogTextName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddSubDialogLicense, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(AddSubDialogTextLicense))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddSubDialogContact, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddSubDialogTextContact))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddSubDialogCarModel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddSubDialogTextCarModel))
                .addGap(18, 18, 18)
                .addComponent(AddSubDialogTextDays)
                .addGap(18, 18, 18)
                .addGroup(AddSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddSubDialogBox1)
                    .addComponent(AddSubDialogBox2)
                    .addComponent(AddSubDialogIsMotorBike))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddSubDialogBox3)
                    .addComponent(AddSubDialogBox4))
                .addGroup(AddSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddSubDialogLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(AddSubDialogConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddSubDialogLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AddSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddSubDialogBox5)
                            .addComponent(AddSubDialogBox6))))
                .addGap(35, 35, 35))
        );

        SubscriberView.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        SubscriberView.setTitle("Tabela de Mensalista");
        SubscriberView.setAlwaysOnTop(true);
        SubscriberView.setIconImage(img.getImage());
        SubscriberView.setIconImages(null);
        SubscriberView.setMinimumSize(new java.awt.Dimension(800, 480));

        SubTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Qntd.", "Nome", "Contato", "Placa", "Modelo do Carro", "Dias", "Dia de Início", "Dia de finalização", "Mensalista", "Moto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        SubTable.setMinimumSize(new java.awt.Dimension(800, 480));
        jScrollPane1.setViewportView(SubTable);
        if (SubTable.getColumnModel().getColumnCount() > 0) {
            SubTable.getColumnModel().getColumn(0).setMinWidth(30);
            SubTable.getColumnModel().getColumn(0).setMaxWidth(30);
            SubTable.getColumnModel().getColumn(8).setPreferredWidth(35);
            SubTable.getColumnModel().getColumn(9).setPreferredWidth(35);
        }

        javax.swing.GroupLayout SubscriberViewLayout = new javax.swing.GroupLayout(SubscriberView.getContentPane());
        SubscriberView.getContentPane().setLayout(SubscriberViewLayout);
        SubscriberViewLayout.setHorizontalGroup(
            SubscriberViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SubscriberViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
                .addContainerGap())
        );
        SubscriberViewLayout.setVerticalGroup(
            SubscriberViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubscriberViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addContainerGap())
        );

        RemoveVeicDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        RemoveVeicDialog.setTitle("Remover Veículo");
        RemoveVeicDialog.setAlwaysOnTop(true);
        RemoveVeicDialog.setIconImage(img.getImage());
        RemoveVeicDialog.setMinimumSize(new java.awt.Dimension(400, 300));
        RemoveVeicDialog.setResizable(false);

        RemoveVeicDialogConfirmButton.setText("Remover");
        RemoveVeicDialogConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveVeicDialogConfirmButtonActionPerformed(evt);
            }
        });

        RemoveVeicDialogComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        RemoveVeicDialogComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveVeicDialogComboBoxActionPerformed(evt);
            }
        });

        RemoveVeicDialogLabel.setText("Hora de Saída (Opcional)");

        javax.swing.GroupLayout RemoveVeicDialogLayout = new javax.swing.GroupLayout(RemoveVeicDialog.getContentPane());
        RemoveVeicDialog.getContentPane().setLayout(RemoveVeicDialogLayout);
        RemoveVeicDialogLayout.setHorizontalGroup(
            RemoveVeicDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RemoveVeicDialogLayout.createSequentialGroup()
                .addContainerGap(276, Short.MAX_VALUE)
                .addComponent(RemoveVeicDialogConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(RemoveVeicDialogLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(RemoveVeicDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RemoveVeicDialogComboBox, 0, 174, Short.MAX_VALUE)
                    .addComponent(RemoveVeicDialogTextField))
                .addGap(39, 39, 39)
                .addComponent(RemoveVeicDialogLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RemoveVeicDialogLayout.setVerticalGroup(
            RemoveVeicDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RemoveVeicDialogLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(RemoveVeicDialogComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(RemoveVeicDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RemoveVeicDialogTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RemoveVeicDialogLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(RemoveVeicDialogConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        RemoveSubDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        RemoveSubDialog.setAlwaysOnTop(true);
        RemoveSubDialog.setIconImage(img.getImage());
        RemoveSubDialog.setMinimumSize(new java.awt.Dimension(400, 300));

        RemoveSubDialogComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        RemoveSubDialogConfirmButton.setText("Remover");
        RemoveSubDialogConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveSubDialogConfirmButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RemoveSubDialogLayout = new javax.swing.GroupLayout(RemoveSubDialog.getContentPane());
        RemoveSubDialog.getContentPane().setLayout(RemoveSubDialogLayout);
        RemoveSubDialogLayout.setHorizontalGroup(
            RemoveSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RemoveSubDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RemoveSubDialogConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(RemoveSubDialogLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(RemoveSubDialogComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(229, Short.MAX_VALUE))
        );
        RemoveSubDialogLayout.setVerticalGroup(
            RemoveSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RemoveSubDialogLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(RemoveSubDialogComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addComponent(RemoveSubDialogConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        EditVeicDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        EditVeicDialog.setTitle("Editar veículo");
        EditVeicDialog.setAlwaysOnTop(true);
        EditVeicDialog.setIconImage(img.getImage());
        EditVeicDialog.setMinimumSize(new java.awt.Dimension(400, 350));
        EditVeicDialog.setResizable(false);

        EditVeicDialogConfirmButton.setText("Editar");
        EditVeicDialogConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditVeicDialogConfirmButtonActionPerformed(evt);
            }
        });

        EditVeicDialogFieldLicense.setToolTipText("");

        EditVeicDialogTextLicense.setText("Placa");

        EditVeicDialogTextTimeIn.setText("Horário de entrada");

        EditVeicDialogTextTimeOut.setText("Horário de Saída");

        EditVeicDialogCheckBoxSub.setText("Mensalista");

        EditVeicDialogCheckBoxHasKey.setText("Chave");
        EditVeicDialogCheckBoxHasKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditVeicDialogCheckBoxHasKeyActionPerformed(evt);
            }
        });

        EditVeicDialogCheckBoxMoto.setText("Moto");
        EditVeicDialogCheckBoxMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditVeicDialogCheckBoxMotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EditVeicDialogLayout = new javax.swing.GroupLayout(EditVeicDialog.getContentPane());
        EditVeicDialog.getContentPane().setLayout(EditVeicDialogLayout);
        EditVeicDialogLayout.setHorizontalGroup(
            EditVeicDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditVeicDialogLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(EditVeicDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EditVeicDialogLayout.createSequentialGroup()
                        .addGroup(EditVeicDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EditVeicDialogComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EditVeicDialogFieldLicense)
                            .addComponent(EditVeicDialogFieldTimeIn, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(EditVeicDialogFieldTimeOut, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(EditVeicDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EditVeicDialogTextLicense)
                            .addComponent(EditVeicDialogTextTimeIn)
                            .addComponent(EditVeicDialogTextTimeOut)
                            .addComponent(EditVeicDialogCheckBoxHasKey))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(EditVeicDialogLayout.createSequentialGroup()
                        .addComponent(EditVeicDialogCheckBoxSub)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(EditVeicDialogLayout.createSequentialGroup()
                        .addComponent(EditVeicDialogCheckBoxMoto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EditVeicDialogConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );
        EditVeicDialogLayout.setVerticalGroup(
            EditVeicDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditVeicDialogLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(EditVeicDialogComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(EditVeicDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditVeicDialogFieldLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditVeicDialogTextLicense))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EditVeicDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditVeicDialogFieldTimeIn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditVeicDialogTextTimeIn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EditVeicDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditVeicDialogFieldTimeOut, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditVeicDialogTextTimeOut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EditVeicDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditVeicDialogCheckBoxSub)
                    .addComponent(EditVeicDialogCheckBoxHasKey, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EditVeicDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EditVeicDialogConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditVeicDialogCheckBoxMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        EditSubDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        EditSubDialog.setTitle("Editar Mensalista");
        EditSubDialog.setAlwaysOnTop(true);
        EditSubDialog.setForeground(java.awt.Color.darkGray);
        EditSubDialog.setIconImage(img.getImage());
        EditSubDialog.setMinimumSize(new java.awt.Dimension(410, 400));
        EditSubDialog.setName("EditSubDialog"); // NOI18N
        EditSubDialog.setResizable(false);

        EditSubDialogCheckBoxIsMensalist.setText("Mensalista");

        EditSubDialogCheckBoxIsMoto.setText("Moto");

        EditSubDialogCheckBoxQua.setText("Qua");

        EditSubDialogCheckBoxQui.setText("Qui");

        EditSubDialogCheckBoxSex.setText("Sex");

        EditSubDialogCheckBoxPNT.setText("PNT");

        EditSubDialogCheckBoxSeg.setText("Seg");

        EditSubDialogCheckBoxTer.setText("Ter");

        EditSubDialogConfirmButton.setText("Confirmar");
        EditSubDialogConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditSubDialogConfirmButtonActionPerformed(evt);
            }
        });

        EditSubDIalogLabelContact.setText("Contato");

        EditSubDIalogLabelLicense.setText("Placa");

        EditSubDIalogLabelName.setText("Nome");

        EditSubDIalogLabelCarModel.setText("Modelo do carro");

        EditSubDIalogLabelSubDate.setText("Data de início");

        EditSubDIalogLabelSubDeadLine.setText("Data final");

        javax.swing.GroupLayout EditSubDialogLayout = new javax.swing.GroupLayout(EditSubDialog.getContentPane());
        EditSubDialog.getContentPane().setLayout(EditSubDialogLayout);
        EditSubDialogLayout.setHorizontalGroup(
            EditSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditSubDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EditSubDialogConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(EditSubDialogLayout.createSequentialGroup()
                .addGroup(EditSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EditSubDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(EditSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EditSubDialogFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(EditSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(EditSubDialogFieldSubDate, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(EditSubDialogFieldCarModel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(5, 5, 5)
                        .addGroup(EditSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EditSubDIalogLabelSubDate)
                            .addComponent(EditSubDIalogLabelCarModel)
                            .addComponent(EditSubDIalogLabelName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(EditSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EditSubDialogFieldSubDeadLine, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditSubDialogFieldLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditSubDialogFieldContact, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(EditSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EditSubDIalogLabelContact)
                            .addComponent(EditSubDIalogLabelLicense)
                            .addComponent(EditSubDIalogLabelSubDeadLine)))
                    .addGroup(EditSubDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(EditSubDialogCheckBoxQua)
                        .addGap(18, 18, 18)
                        .addComponent(EditSubDialogCheckBoxPNT))
                    .addGroup(EditSubDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(EditSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EditSubDialogCheckBoxSeg)
                            .addComponent(EditSubDialogCheckBoxTer))
                        .addGap(18, 18, 18)
                        .addGroup(EditSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EditSubDialogCheckBoxSex)
                            .addComponent(EditSubDialogCheckBoxQui))
                        .addGap(101, 101, 101)
                        .addGroup(EditSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EditSubDialogCheckBoxIsMensalist)
                            .addComponent(EditSubDialogCheckBoxIsMoto)))
                    .addGroup(EditSubDialogLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(EditSubDialogComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        EditSubDialogLayout.setVerticalGroup(
            EditSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditSubDialogLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(EditSubDialogComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(EditSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditSubDialogFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditSubDialogFieldSubDeadLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditSubDIalogLabelName)
                    .addComponent(EditSubDIalogLabelSubDeadLine))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EditSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditSubDialogFieldCarModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditSubDialogFieldContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditSubDIalogLabelContact)
                    .addComponent(EditSubDIalogLabelCarModel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EditSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditSubDialogFieldSubDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditSubDialogFieldLicense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditSubDIalogLabelLicense)
                    .addComponent(EditSubDIalogLabelSubDate))
                .addGap(42, 42, 42)
                .addGroup(EditSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditSubDialogCheckBoxIsMensalist)
                    .addComponent(EditSubDialogCheckBoxQui)
                    .addComponent(EditSubDialogCheckBoxSeg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EditSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditSubDialogCheckBoxIsMoto)
                    .addComponent(EditSubDialogCheckBoxSex)
                    .addComponent(EditSubDialogCheckBoxTer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EditSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditSubDialogCheckBoxQua)
                    .addComponent(EditSubDialogCheckBoxPNT))
                .addGap(18, 18, 18)
                .addComponent(EditSubDialogConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Controle de Veículos");
        setAlwaysOnTop(true);
        setForeground(java.awt.Color.lightGray);
        setIconImage(img.getImage());
        setMinimumSize(new java.awt.Dimension(800, 700));
        setName("mainMenu"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        AddVeic.setText("Adicionar Veículo");
        AddVeic.setPreferredSize(new java.awt.Dimension(70, 20));
        AddVeic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddVeicActionPerformed(evt);
            }
        });

        ScrollPaneTable.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        ScrollPaneTable.setMinimumSize(new java.awt.Dimension(300, 550));
        ScrollPaneTable.setPreferredSize(new java.awt.Dimension(300, 550));

        mainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Qntd.", "Placa", "Entrada", "Saída", "Mensalista", "Chave"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        mainTable.setMinimumSize(new java.awt.Dimension(300, 550));
        mainTable.setPreferredSize(new java.awt.Dimension(300, 550));
        mainTable.setShowGrid(true);
        ScrollPaneTable.setViewportView(mainTable);
        if (mainTable.getColumnModel().getColumnCount() > 0) {
            mainTable.getColumnModel().getColumn(0).setMinWidth(30);
            mainTable.getColumnModel().getColumn(0).setMaxWidth(30);
            mainTable.getColumnModel().getColumn(4).setMinWidth(30);
            mainTable.getColumnModel().getColumn(4).setMaxWidth(30);
            mainTable.getColumnModel().getColumn(5).setMinWidth(30);
            mainTable.getColumnModel().getColumn(5).setMaxWidth(30);
        }

        AddSub.setText("Adicionar Mensalista");
        AddSub.setPreferredSize(new java.awt.Dimension(70, 20));
        AddSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSubActionPerformed(evt);
            }
        });

        DesktopPane.setMinimumSize(new java.awt.Dimension(400, 550));

        javax.swing.GroupLayout DesktopPaneLayout = new javax.swing.GroupLayout(DesktopPane);
        DesktopPane.setLayout(DesktopPaneLayout);
        DesktopPaneLayout.setHorizontalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        DesktopPaneLayout.setVerticalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        RemoveSub.setText("Remover Mensalista");
        RemoveSub.setPreferredSize(new java.awt.Dimension(70, 20));
        RemoveSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveSubActionPerformed(evt);
            }
        });

        RemoveVeic.setText("Remover Veículo");
        RemoveVeic.setPreferredSize(new java.awt.Dimension(70, 20));
        RemoveVeic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveVeicActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        menubarNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menubarNew.setText("New");
        menubarNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menubarNewActionPerformed(evt);
            }
        });
        jMenu1.add(menubarNew);

        menubarOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menubarOpen.setText("Open");
        menubarOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menubarOpenActionPerformed(evt);
            }
        });
        jMenu1.add(menubarOpen);

        menubarSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menubarSave.setText("Save");
        menubarSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menubarSaveActionPerformed(evt);
            }
        });
        jMenu1.add(menubarSave);

        menubarNewWindow.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menubarNewWindow.setText("New Window");
        menubarNewWindow.setName("New Window"); // NOI18N
        menubarNewWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menubarNewWindowActionPerformed(evt);
            }
        });
        jMenu1.add(menubarNewWindow);

        MenuBar.add(jMenu1);

        jMenu2.setText("Edit");

        EditMenuEditVeic.setText("Editar Veículo");
        EditMenuEditVeic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditMenuEditVeicActionPerformed(evt);
            }
        });
        jMenu2.add(EditMenuEditVeic);

        EditMenuEditSub.setText("Editar Mensalista");
        EditMenuEditSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditMenuEditSubActionPerformed(evt);
            }
        });
        jMenu2.add(EditMenuEditSub);

        MenuBar.add(jMenu2);

        jMenu3.setText("View");

        ViewMenuSubscriberView.setText("Mensalistas");
        ViewMenuSubscriberView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewMenuSubscriberViewActionPerformed(evt);
            }
        });
        jMenu3.add(ViewMenuSubscriberView);

        MenuBar.add(jMenu3);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPaneTable, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AddVeic, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(AddSub, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(DesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RemoveVeic, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RemoveSub, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollPaneTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddSub, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddVeic, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RemoveSub, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RemoveVeic, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(DesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 442, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddVeicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddVeicActionPerformed
        // TODO add your handling code here:
        
        AddVeicDialog.setLocation(DesktopPane.getLocationOnScreen());
        AddVeicDialog.setVisible(true);
        //AddVeicDialogConfirmButton.setFocusTraversalKeys(WIDTH, );
        
    }//GEN-LAST:event_AddVeicActionPerformed

    private void AddSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSubActionPerformed
        AddSubDialog.setLocation(DesktopPane.getLocationOnScreen());
        AddSubDialog.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_AddSubActionPerformed

    private void menubarNewWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menubarNewWindowActionPerformed
        // TODO add your handling code here:
        new Thread(){
        @Override
        public void run(){
            
            MainMenu aux = new MainMenu();
            aux.setVisible(true);
            
            }
        
        }.start();
        
        //ainda n ta 100%
        
    }//GEN-LAST:event_menubarNewWindowActionPerformed

    private void menubarOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menubarOpenActionPerformed
        // TODO add your handling code here:
        this.SaveLoadDialog.showOpenDialog(MainMenu.this);
        File file = this.SaveLoadDialog.getSelectedFile();
        String filepath = file.getAbsolutePath();
        this.list = new ArquivesManagement().LoadFile(filepath);
        
        
    }//GEN-LAST:event_menubarOpenActionPerformed

    private void menubarSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menubarSaveActionPerformed
        // TODO add your handling code here:
        ArquivesManagement arq = new ArquivesManagement();
        arq.AutoSave(veiculeList, subscriberList);
        
    }//GEN-LAST:event_menubarSaveActionPerformed

    private void menubarNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menubarNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menubarNewActionPerformed

    private void AddVeicDialogLicenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddVeicDialogLicenseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddVeicDialogLicenseActionPerformed

    private void AddVeicDialogConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddVeicDialogConfirmButtonActionPerformed
        // TODO add your handling code here:
        VeiculeClass veic = new VeiculeClass();
        veic.setLicense(AddVeicDialogLicense.getText().toUpperCase());
        if(AddVeicDialogManualTime.getText() == null || "".equals(AddVeicDialogManualTime.getText())){
            veic.setAutoTimeIn();
        }
        else{
            veic.setManualTimeIn(AddVeicDialogManualTime.getText());
        }
        if(AddVeicDialogSubscriber.isSelected() == true){
            veic.setManualIsSubscriber(true);
        }
        else{
            veic.setIsSubscriber(subscriberList);
        }
        if(AddVeicDialogHasKey.isSelected() == true){
            veic.setHasKey(true);
        }
        else{
            veic.setHasKey(false);
        }
        if(AddVeicDialogIsMotorBike.isSelected()==true){
            veic.setIsMotorBike(true);
        }
        else{
            veic.setIsMotorBike(false);
        }
        
        //veic.setIsSubscriber(subscriberList);
        
        
        veic.setDate();
        
        veiculeList.add(veic);
        this.updateTable();
        this.db.insertIntoVeicule(veic);
        
        
        
        AddVeicDialog.dispose();
        AddVeicDialogLicense.setText("");
        AddVeicDialogManualTime.setText("");
        AddVeicDialogSubscriber.setSelected(false);
        AddVeicDialogHasKey.setSelected(false);
        
        
    }//GEN-LAST:event_AddVeicDialogConfirmButtonActionPerformed

    private void AddVeicDialogManualTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddVeicDialogManualTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddVeicDialogManualTimeActionPerformed

    private void AddSubDialogNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSubDialogNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddSubDialogNameActionPerformed

    private void AddSubDialogCarModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSubDialogCarModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddSubDialogCarModelActionPerformed

    private void AddSubDialogConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSubDialogConfirmButtonActionPerformed
        // TODO add your handling code here:
        String aux ="";
        Subscriber sub = new Subscriber();
        sub.setName(AddSubDialogName.getText());
        sub.setAutoSubscriptionDate();
        sub.setContact(AddSubDialogContact.getText());
        if(AddSubDialogLicense.getText() != null){
            sub.setLicense(AddSubDialogLicense.getText());
        }
        if(AddSubDialogCarModel.getText() != null){
            sub.setCarModel(AddSubDialogCarModel.getText());
        }
        
        
        
        //CheckBox ifs
        if(AddSubDialogBox1.isSelected() == true){
            aux = aux + "Seg ";
        }
        if(AddSubDialogBox2.isSelected() == true){
            aux = aux + "Ter ";
        }
        if(AddSubDialogBox3.isSelected() == true){
            aux = aux + "Qua ";
        }
        if(AddSubDialogBox4.isSelected() == true){
            aux = aux + "Qui ";
        }
        if(AddSubDialogBox5.isSelected() == true){
            aux = aux + "Sex ";
        }
        if(AddSubDialogBox6.isSelected() == true){
            aux = aux + "PNT.";
        }
        if(AddSubDialogIsMotorBike.isSelected() == true){
            sub.setIsMotorBike(true);
        }
        else{
            sub.setIsMotorBike(false);
        }
        
        
        
        
        sub.setWeekDays(aux);
        sub.setAutoSubscriptionDeadLine();
        sub.setAutoIsMensalist();
        
        
        //sub.setAutoSubscriptionDeadLine();
        System.out.println(sub.getName() + " " + sub.getSubscriptionDate() + " " + sub.getContact());
        
        subscriberList.add(sub);
        AddSubDialog.dispose();
        AddSubDialogName.setText("");
        AddSubDialogLicense.setText("");
        AddSubDialogContact.setText("");
        AddSubDialogCarModel.setText("");
        AddSubDialogBox1.setSelected(false);
        AddSubDialogBox2.setSelected(false);
        AddSubDialogBox3.setSelected(false);
        AddSubDialogBox4.setSelected(false);
        AddSubDialogBox5.setSelected(false);
        AddSubDialogBox6.setSelected(false);
        
        this.db.insertIntoSubscriber(sub);
        
        
    }//GEN-LAST:event_AddSubDialogConfirmButtonActionPerformed

    private void ViewMenuSubscriberViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewMenuSubscriberViewActionPerformed
        // TODO add your handling code here:
        
        
        
        SubscriberView.setVisible(true);
        this.updateTable();
        /*
        int aux = 1;
        for(int i = 0; i<subscriberList.size(); i = i+1){
            subscriberList.get(i).setAutoIsMensalist();
            
            SubTable.setValueAt(aux, i, 0);
            SubTable.setValueAt(subscriberList.get(i).getName(), i, 1);
            SubTable.setValueAt(subscriberList.get(i).getContact(), i, 2);
            SubTable.setValueAt(subscriberList.get(i).getLicense().toUpperCase(), i, 3);
            SubTable.setValueAt(subscriberList.get(i).getCarModel(), i, 4);
            SubTable.setValueAt(subscriberList.get(i).getWeekDays(), i, 5);
            SubTable.setValueAt(subscriberList.get(i).getSubscriptionDate(), i, 6);
            SubTable.setValueAt(subscriberList.get(i).getSubscriptionDeadLine(), i, 7);
            SubTable.setValueAt(subscriberList.get(i).getIsMensalist(), i, 8);
            
            aux = aux+1;
            
        }
        */
        
        
        
        
        
        
        
    }//GEN-LAST:event_ViewMenuSubscriberViewActionPerformed

    private void RemoveSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveSubActionPerformed
        // TODO add your handling code here:
        RemoveSubDialog.setLocation(DesktopPane.getLocationOnScreen());
        RemoveSubDialog.setVisible(true);
        RemoveSubDialogComboBox.removeAllItems();
        for(int i = 0; i<subscriberList.size(); i = i+1){
            RemoveSubDialogComboBox.addItem(subscriberList.get(i).getName());
            
        
        }
        RemoveSubDialog.addWindowListener(new java.awt.event.WindowAdapter(){
            @Override
            public void windowClosing(java.awt.event.WindowEvent e){
                RemoveSubDialogComboBox.removeAllItems();
                RemoveSubDialog.dispose();
                
            }
        });
    }//GEN-LAST:event_RemoveSubActionPerformed

    private void RemoveVeicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveVeicActionPerformed
        //var db = new DataBaseManagement();
        RemoveVeicDialog.setLocation(DesktopPane.getLocationOnScreen());
        RemoveVeicDialog.setVisible(true);
        for(int i = 0; i<veiculeList.size(); i = i+1){
            if(veiculeList.get(i).getTimeOut() == null){
                RemoveVeicDialogComboBox.addItem(veiculeList.get(i).getLicense());
            }
        
        }
        RemoveVeicDialog.addWindowListener(new java.awt.event.WindowAdapter(){
            @Override
            public void windowClosing(java.awt.event.WindowEvent e){
                RemoveVeicDialogComboBox.removeAllItems();
                RemoveVeicDialog.dispose();
                
            }
        });
        
        
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_RemoveVeicActionPerformed

    private void EditMenuEditVeicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditMenuEditVeicActionPerformed
        // TODO add your handling code here:
        EditVeicDialog.setLocation(DesktopPane.getLocationOnScreen());
        EditVeicDialog.show();
        EditVeicDialogComboBox.removeAllItems();
        for(int i = 0; i<veiculeList.size(); i = i+1){
        
                EditVeicDialogComboBox.addItem(veiculeList.get(i).getLicense());    
        }
        EditVeicDialog.addWindowListener(new java.awt.event.WindowAdapter(){
            @Override
            public void windowClosing(java.awt.event.WindowEvent e){
                EditVeicDialogComboBox.removeAllItems();
                EditVeicDialog.dispose();
                
            }
        });
        
        EditVeicDialogFieldLicense.setText("");        
        EditVeicDialogFieldTimeIn.setText("");
        EditVeicDialogFieldTimeOut.setText("");
        EditVeicDialogCheckBoxSub.setSelected(false);
        EditVeicDialogCheckBoxHasKey.setSelected(false);
        EditVeicDialogCheckBoxMoto.setSelected(false);
    }//GEN-LAST:event_EditMenuEditVeicActionPerformed

    private void RemoveVeicDialogConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveVeicDialogConfirmButtonActionPerformed
        // TODO add your handling code here:
        
        
        //TEM DB aqui
        int i = 0;
        var veicOld = new VeiculeClass();
        String aux = RemoveVeicDialogComboBox.getSelectedItem().toString();
        int auxint = RemoveVeicDialogComboBox.getSelectedIndex();
        
        
        
        if(aux.equals(veiculeList.get(auxint).getLicense())){
            veicOld.setLicense(aux);
            veicOld.setDate();
        }
        else{
            int j = 0;
            while(!aux.equals(veiculeList.get(j).getLicense())){
                j = j +1;
            }
            veicOld.setLicense(aux);
            veicOld.setDate();
        }
        
        
        if(aux.equals(veiculeList.get(auxint).getLicense())){
            i = auxint;
            if("".equals(RemoveVeicDialogTextField.getText())){
                veiculeList.get(auxint).setAutoTimeOut();
                
            }
            else{
                veiculeList.get(auxint).setManualTimeOut(RemoveVeicDialogTextField.getText());
            }
        }
            
                  
            
        else{
            
            while(!aux.equals(veiculeList.get(i).getLicense())){
                i = i+1;
            }
            if("".equals(RemoveVeicDialogTextField.getText())){
                veiculeList.get(i).setAutoTimeOut();
            }
            else{
                veiculeList.get(i).setManualTimeOut(RemoveVeicDialogTextField.getText());
            }
        }
        
        
        
        
        RemoveVeicDialogComboBox.removeAllItems();
        RemoveVeicDialog.dispose();
        
        
        this.db.updateItemFromVeicule(veicOld, veiculeList.get(i));
        this.updateTable();
        
    }//GEN-LAST:event_RemoveVeicDialogConfirmButtonActionPerformed

    private void RemoveVeicDialogComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveVeicDialogComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RemoveVeicDialogComboBoxActionPerformed

    private void RemoveSubDialogConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveSubDialogConfirmButtonActionPerformed
        // TODO add your handling code here:
        String aux = RemoveSubDialogComboBox.getSelectedItem().toString();
        int auxint = RemoveSubDialogComboBox.getSelectedIndex();
        
        if(aux.equals(subscriberList.get(auxint).getName())){
            subscriberList.remove(auxint);
            //é preciso trabalhar com banco de dados aqui.
            
            
        }
        else{
            int i = 0;
            while(!aux.equals(subscriberList.get(i).getName())){
                i = i+1;
            }
            subscriberList.remove(i);
        }
        
        RemoveSubDialogComboBox.removeAllItems();
        RemoveSubDialog.dispose();
        
        this.clearTable();
        
        
        
        
    }//GEN-LAST:event_RemoveSubDialogConfirmButtonActionPerformed

    private void EditMenuEditSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditMenuEditSubActionPerformed
        // TODO add your handling code here:
        EditSubDialog.setLocation(DesktopPane.getLocationOnScreen());
        EditSubDialog.show();
        EditSubDialogComboBox.removeAllItems();
        for(int i = 0; i<subscriberList.size(); i = i+1){
        
                EditSubDialogComboBox.addItem(subscriberList.get(i).getName());    
        }
        EditSubDialog.addWindowListener(new java.awt.event.WindowAdapter(){
            @Override
            public void windowClosing(java.awt.event.WindowEvent e){
                EditSubDialogComboBox.removeAllItems();
                EditSubDialog.dispose();
                
            }
        });
        
        
        
        
        EditSubDialogFieldName.setText("");
        EditSubDialogFieldCarModel.setText("");
        EditSubDialogFieldSubDate.setText("");
        EditSubDialogFieldSubDeadLine.setText("");
        EditSubDialogFieldContact.setText("");
        EditSubDialogFieldLicense.setText("");
        EditSubDialogCheckBoxSeg.setSelected(false);
        EditSubDialogCheckBoxTer.setSelected(false);
        EditSubDialogCheckBoxQua.setSelected(false);
        EditSubDialogCheckBoxQui.setSelected(false);
        EditSubDialogCheckBoxSex.setSelected(false);
        EditSubDialogCheckBoxPNT.setSelected(false);
        EditSubDialogCheckBoxIsMensalist.setSelected(false);
        EditSubDialogCheckBoxIsMoto.setSelected(false);
        
        
        
    }//GEN-LAST:event_EditMenuEditSubActionPerformed

    private void EditVeicDialogConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditVeicDialogConfirmButtonActionPerformed
        // TODO add your handling code here:
        
        //TEM DB aqui
        
        var veicOld = new VeiculeClass();
        String aux = EditVeicDialogComboBox.getSelectedItem().toString();
        int auxint = EditVeicDialogComboBox.getSelectedIndex();
        
        
        if(aux.equals(veiculeList.get(auxint).getLicense())){
            veicOld.setLicense(aux);
            veicOld.setDate();
        }
        
        if(aux.equals(veiculeList.get(auxint).getLicense())){
            if(!"".equals(EditVeicDialogFieldLicense.getText())){
                veiculeList.get(auxint).setLicense(EditVeicDialogFieldLicense.getText());
                
            }
            if(!"".equals(EditVeicDialogFieldTimeIn.getText())){
                veiculeList.get(auxint).setManualTimeIn(EditVeicDialogFieldTimeIn.getText());
                
            }
            if(!"".equals(EditVeicDialogFieldTimeOut.getText())){
                veiculeList.get(auxint).setManualTimeOut(EditVeicDialogFieldTimeOut.getText());
                
            }
            
        }
        
        EditVeicDialog.dispose();
        
        EditVeicDialogComboBox.removeAllItems();
        this.db.updateItemFromVeicule(veicOld, veiculeList.get(auxint));
        this.updateTable();
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_EditVeicDialogConfirmButtonActionPerformed

    private void EditVeicDialogCheckBoxMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditVeicDialogCheckBoxMotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditVeicDialogCheckBoxMotoActionPerformed

    private void EditVeicDialogCheckBoxHasKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditVeicDialogCheckBoxHasKeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditVeicDialogCheckBoxHasKeyActionPerformed

    private void EditSubDialogConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditSubDialogConfirmButtonActionPerformed
        // TODO add your handling code here:
        //Create a update LOG table.
        Subscriber subOld = new Subscriber();
        String aux = EditSubDialogComboBox.getSelectedItem().toString();
        int auxint = EditSubDialogComboBox.getSelectedIndex();
        if(aux.equals(subscriberList.get(auxint).getName())){
            subOld.setName(aux);
        }
        
        
        if(aux.equals(subscriberList.get(auxint).getName())){
            
            
            if(!"".equals(EditSubDialogFieldName.getText())){
                subscriberList.get(auxint).setName(EditSubDialogFieldName.getText());
            }
            if(!"".equals(EditSubDialogFieldCarModel.getText())){
                subscriberList.get(auxint).setCarModel(EditSubDialogFieldCarModel.getText());
            }
            if(!"".equals(EditSubDialogFieldSubDate.getText())){
                subscriberList.get(auxint).setManualSubscriptionDate(EditSubDialogFieldSubDate.getText());
                subscriberList.get(auxint).setAutoSubscriptionDeadLine();
            }
            if(!"".equals(EditSubDialogFieldSubDeadLine.getText())){
                subscriberList.get(auxint).setManualSubscriptionDeadLine(EditSubDialogFieldSubDeadLine.getText());
            }
            if(!"".equals(EditSubDialogFieldContact.getText())){
                subscriberList.get(auxint).setContact(EditSubDialogFieldContact.getText());
            }
            if(!"".equals(EditSubDialogFieldLicense.getText())){
                subscriberList.get(auxint).setLicense(EditSubDialogFieldLicense.getText());
            }
            
            //If gigantesco faz com que, qualquer das caixas selecionadas, irá zerar o valor do weekdays
            //e poderá armazenadr os valores que estão marcados:
            if(EditSubDialogCheckBoxSeg.isSelected() == true || EditSubDialogCheckBoxTer.isSelected() == true
            || EditSubDialogCheckBoxQua.isSelected() == true || EditSubDialogCheckBoxQui.isSelected() == true 
            || EditSubDialogCheckBoxSex.isSelected() == true || EditSubDialogCheckBoxPNT.isSelected() == true){
                subscriberList.get(auxint).setWeekDays(null);
                //Inicio dos If de atribuição.
                String straux = "";
                
                if(EditSubDialogCheckBoxSeg.isSelected() == true){
                straux = straux + "Seg ";
                }
                if(EditSubDialogCheckBoxTer.isSelected() == true){
                straux = straux + "Ter ";
                }
                if(EditSubDialogCheckBoxQua.isSelected() == true){
                straux = straux + "Qua ";
                }
                if(EditSubDialogCheckBoxQui.isSelected() == true){
                straux = straux + "Qui ";
                }
                if(EditSubDialogCheckBoxSex.isSelected() == true){
                straux = straux + "Sex ";
                }
                if(EditSubDialogCheckBoxPNT.isSelected() == true){
                straux = straux + "PNT.";
                }
                
                subscriberList.get(auxint).setWeekDays(straux);
               
            }
            
            if(EditSubDialogCheckBoxIsMensalist.isSelected() == true){
                subscriberList.get(auxint).setIsMensalist(true);
            }
            
            if(EditSubDialogCheckBoxIsMoto.isSelected() == true){
                subscriberList.get(auxint).setIsMotorBike(true);
            }
        }
            
        
        EditSubDialog.dispose();
        
        EditSubDialogComboBox.removeAllItems();
        this.updateTable();
        this.db.updateItemFromSubscriber(subOld, subscriberList.get(auxint));

        
    }//GEN-LAST:event_EditSubDialogConfirmButtonActionPerformed
    
    
    
    
    
    public void updateTable(){
        int aux = 1;
        
        
        for(int i = 0; i<subscriberList.size(); i = i+1){
            subscriberList.get(i).setAutoIsMensalist();
            
            SubTable.setValueAt(aux, i, 0);
            SubTable.setValueAt(subscriberList.get(i).getName(), i, 1);
            SubTable.setValueAt(subscriberList.get(i).getContact(), i, 2);
            SubTable.setValueAt(subscriberList.get(i).getLicense().toUpperCase(), i, 3);
            SubTable.setValueAt(subscriberList.get(i).getCarModel(), i, 4);
            SubTable.setValueAt(subscriberList.get(i).getWeekDays(), i, 5);
            SubTable.setValueAt(subscriberList.get(i).getSubscriptionDate(), i, 6);
            SubTable.setValueAt(subscriberList.get(i).getSubscriptionDeadLine(), i, 7);
            SubTable.setValueAt(subscriberList.get(i).getIsMensalist(), i, 8);
            
            
            aux = aux+1;
            
        }
        aux = 1;
        for(int i = 0; i<veiculeList.size(); i = i+1){
            veiculeList.get(i).setIsSubscriber(subscriberList);
            mainTable.setValueAt(aux, i, 0);
            mainTable.setValueAt(veiculeList.get(i).getLicense().toUpperCase(), i, 1);
            mainTable.setValueAt(veiculeList.get(i).getTimeIn(), i, 2);
            mainTable.setValueAt(veiculeList.get(i).getTimeOut(), i, 3);
            mainTable.setValueAt(veiculeList.get(i).getIsSubscriber(), i, 4);
            mainTable.setValueAt(veiculeList.get(i).getHasKey(), i, 5);
            
            aux = aux + 1;
        }
        
        
    }
    
    public void clearTable(){
        for(int i = 0; i< subscriberList.size()+1; i = i + 1){
            SubTable.setValueAt(null, i, 0);
            SubTable.setValueAt(null, i, 1);
            SubTable.setValueAt(null, i, 2);
            SubTable.setValueAt(null, i, 3);
            SubTable.setValueAt(null, i, 4);
            SubTable.setValueAt(null, i, 5);
            SubTable.setValueAt(null, i, 6);
            SubTable.setValueAt(null, i, 7);
            SubTable.setValueAt(null, i, 8);
            
        }
        
        
    }
    
    
    public void multipageTable(){
        if(subscriberList.size()<100){
            return;
        }
        else{
            //fazer a logica para mudar de pagina da tabela aqui
            //bem complicado isso.
        }
    }
    
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddSub;
    private javax.swing.JDialog AddSubDialog;
    private javax.swing.JCheckBox AddSubDialogBox1;
    private javax.swing.JCheckBox AddSubDialogBox2;
    private javax.swing.JCheckBox AddSubDialogBox3;
    private javax.swing.JCheckBox AddSubDialogBox4;
    private javax.swing.JCheckBox AddSubDialogBox5;
    private javax.swing.JCheckBox AddSubDialogBox6;
    private javax.swing.JTextField AddSubDialogCarModel;
    private javax.swing.JButton AddSubDialogConfirmButton;
    private javax.swing.JTextField AddSubDialogContact;
    private javax.swing.JCheckBox AddSubDialogIsMotorBike;
    private javax.swing.JTextField AddSubDialogLicense;
    private javax.swing.JTextField AddSubDialogName;
    private javax.swing.JLabel AddSubDialogTextCarModel;
    private javax.swing.JLabel AddSubDialogTextContact;
    private javax.swing.JLabel AddSubDialogTextDays;
    private javax.swing.JLabel AddSubDialogTextLicense;
    private javax.swing.JLabel AddSubDialogTextName;
    private javax.swing.JButton AddVeic;
    private javax.swing.JDialog AddVeicDialog;
    private javax.swing.JToggleButton AddVeicDialogConfirmButton;
    private javax.swing.JCheckBox AddVeicDialogHasKey;
    private javax.swing.JCheckBox AddVeicDialogIsMotorBike;
    private javax.swing.JTextField AddVeicDialogLicense;
    private javax.swing.JTextField AddVeicDialogManualTime;
    private javax.swing.JCheckBox AddVeicDialogSubscriber;
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JMenuItem EditMenuEditSub;
    private javax.swing.JMenuItem EditMenuEditVeic;
    private javax.swing.JLabel EditSubDIalogLabelCarModel;
    private javax.swing.JLabel EditSubDIalogLabelContact;
    private javax.swing.JLabel EditSubDIalogLabelLicense;
    private javax.swing.JLabel EditSubDIalogLabelName;
    private javax.swing.JLabel EditSubDIalogLabelSubDate;
    private javax.swing.JLabel EditSubDIalogLabelSubDeadLine;
    private javax.swing.JDialog EditSubDialog;
    private javax.swing.JCheckBox EditSubDialogCheckBoxIsMensalist;
    private javax.swing.JCheckBox EditSubDialogCheckBoxIsMoto;
    private javax.swing.JCheckBox EditSubDialogCheckBoxPNT;
    private javax.swing.JCheckBox EditSubDialogCheckBoxQua;
    private javax.swing.JCheckBox EditSubDialogCheckBoxQui;
    private javax.swing.JCheckBox EditSubDialogCheckBoxSeg;
    private javax.swing.JCheckBox EditSubDialogCheckBoxSex;
    private javax.swing.JCheckBox EditSubDialogCheckBoxTer;
    private javax.swing.JComboBox<String> EditSubDialogComboBox;
    private javax.swing.JButton EditSubDialogConfirmButton;
    private javax.swing.JTextField EditSubDialogFieldCarModel;
    private javax.swing.JTextField EditSubDialogFieldContact;
    private javax.swing.JTextField EditSubDialogFieldLicense;
    private javax.swing.JTextField EditSubDialogFieldName;
    private javax.swing.JTextField EditSubDialogFieldSubDate;
    private javax.swing.JTextField EditSubDialogFieldSubDeadLine;
    private javax.swing.JDialog EditVeicDialog;
    private javax.swing.JCheckBox EditVeicDialogCheckBoxHasKey;
    private javax.swing.JCheckBox EditVeicDialogCheckBoxMoto;
    private javax.swing.JCheckBox EditVeicDialogCheckBoxSub;
    private javax.swing.JComboBox<String> EditVeicDialogComboBox;
    private javax.swing.JButton EditVeicDialogConfirmButton;
    private javax.swing.JTextField EditVeicDialogFieldLicense;
    private javax.swing.JTextField EditVeicDialogFieldTimeIn;
    private javax.swing.JTextField EditVeicDialogFieldTimeOut;
    private javax.swing.JLabel EditVeicDialogTextLicense;
    private javax.swing.JLabel EditVeicDialogTextTimeIn;
    private javax.swing.JLabel EditVeicDialogTextTimeOut;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JButton RemoveSub;
    private javax.swing.JDialog RemoveSubDialog;
    private javax.swing.JComboBox<String> RemoveSubDialogComboBox;
    private javax.swing.JButton RemoveSubDialogConfirmButton;
    private javax.swing.JButton RemoveVeic;
    private javax.swing.JDialog RemoveVeicDialog;
    private javax.swing.JComboBox<String> RemoveVeicDialogComboBox;
    private javax.swing.JButton RemoveVeicDialogConfirmButton;
    private javax.swing.JLabel RemoveVeicDialogLabel;
    private javax.swing.JTextField RemoveVeicDialogTextField;
    private javax.swing.JFileChooser SaveLoadDialog;
    private javax.swing.JScrollPane ScrollPaneTable;
    private javax.swing.JTable SubTable;
    private javax.swing.JDialog SubscriberView;
    private javax.swing.JLabel TextHorarioDeEntrada;
    private javax.swing.JLabel TextPlacaDoVeiculo;
    private javax.swing.JMenuItem ViewMenuSubscriberView;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable mainTable;
    private javax.swing.JMenuItem menubarNew;
    private javax.swing.JMenuItem menubarNewWindow;
    private javax.swing.JMenuItem menubarOpen;
    private javax.swing.JMenuItem menubarSave;
    // End of variables declaration//GEN-END:variables
    private ArrayList<VeiculeClass> veiculeList = new ArrayList();
    private ArrayList<Subscriber> subscriberList = new ArrayList();
    private ArrayList<Object> list;
    private javax.swing.ImageIcon img = new javax.swing.ImageIcon("icons/2dEstacionamento.png");
    private DataBaseManagement db;

    
}
