/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package parkingcontrol;

import java.io.File;
import java.util.ArrayList;

/**
 *
 * @author davip
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SaveLoadDialog = new javax.swing.JFileChooser();
        AddVeicDialog = new javax.swing.JDialog();
        AddVeicDialogLicense = new javax.swing.JTextField();
        AddVeicDialogManualTime = new javax.swing.JTextField();
        AddVeicDialogSubscriber = new javax.swing.JCheckBox();
        AddVeicDialogHasKey = new javax.swing.JCheckBox();
        AddVeicDialogConfirmButton = new javax.swing.JToggleButton();
        TextPlacaDoVeiculo = new javax.swing.JLabel();
        TextHorarioDeEntrada = new javax.swing.JLabel();
        AddSubDialog = new javax.swing.JDialog();
        AddSubDialogName = new javax.swing.JTextField();
        AddSubDialogLicense = new javax.swing.JTextField();
        AddSubDialogContact = new javax.swing.JTextField();
        AddSubDialogTextName = new javax.swing.JLabel();
        AddSubDialogTextLicense = new javax.swing.JLabel();
        AddSubDialogTextContact = new javax.swing.JLabel();
        AddSubDialogConfirmButton = new javax.swing.JButton();
        AddSubDialogCarModel = new javax.swing.JTextField();
        AddSubDialogTextCarModel = new javax.swing.JLabel();
        AddSubDialogTextDays = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        AddVeic = new javax.swing.JButton();
        ScrollPaneTable = new javax.swing.JScrollPane();
        mainTable = new javax.swing.JTable();
        AddSub = new javax.swing.JButton();
        DesktopPane = new javax.swing.JDesktopPane();
        MenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menubarNew = new javax.swing.JMenuItem();
        menubarOpen = new javax.swing.JMenuItem();
        menubarSave = new javax.swing.JMenuItem();
        menubarNewWindow = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        SaveLoadDialog.setPreferredSize(new java.awt.Dimension(500, 300));

        AddVeicDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        AddVeicDialog.setTitle("Adicionar Veículo");
        AddVeicDialog.setAlwaysOnTop(true);
        AddVeicDialog.setIconImage(null);
        AddVeicDialog.setLocation(DesktopPane.location());
        AddVeicDialog.setMinimumSize(new java.awt.Dimension(400, 300));
        AddVeicDialog.setPreferredSize(new java.awt.Dimension(400, 300));
        AddVeicDialog.setResizable(false);

        AddVeicDialogLicense.setName("Placa do Carro"); // NOI18N
        AddVeicDialogLicense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddVeicDialogLicenseActionPerformed(evt);
            }
        });

        AddVeicDialogManualTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddVeicDialogManualTimeActionPerformed(evt);
            }
        });

        AddVeicDialogSubscriber.setText("Mensalista");

        AddVeicDialogHasKey.setText("Chave do Carro");

        AddVeicDialogConfirmButton.setText("Adicionar");
        AddVeicDialogConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddVeicDialogConfirmButtonActionPerformed(evt);
            }
        });

        TextPlacaDoVeiculo.setText("Placa do Veículo");

        TextHorarioDeEntrada.setText("Horário de Entrada");
        TextHorarioDeEntrada.setToolTipText("");

        javax.swing.GroupLayout AddVeicDialogLayout = new javax.swing.GroupLayout(AddVeicDialog.getContentPane());
        AddVeicDialog.getContentPane().setLayout(AddVeicDialogLayout);
        AddVeicDialogLayout.setHorizontalGroup(
            AddVeicDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddVeicDialogLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(AddVeicDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddVeicDialogLayout.createSequentialGroup()
                        .addComponent(AddVeicDialogSubscriber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AddVeicDialogHasKey))
                    .addGroup(AddVeicDialogLayout.createSequentialGroup()
                        .addGroup(AddVeicDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddVeicDialogLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddVeicDialogManualTime, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AddVeicDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextPlacaDoVeiculo)
                            .addComponent(TextHorarioDeEntrada)
                            .addGroup(AddVeicDialogLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(AddVeicDialogConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AddVeicDialogLayout.setVerticalGroup(
            AddVeicDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddVeicDialogLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(AddVeicDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddVeicDialogLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextPlacaDoVeiculo))
                .addGap(18, 18, 18)
                .addGroup(AddVeicDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddVeicDialogManualTime, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextHorarioDeEntrada))
                .addGap(18, 18, 18)
                .addGroup(AddVeicDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddVeicDialogSubscriber)
                    .addComponent(AddVeicDialogHasKey))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(AddVeicDialogConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        AddSubDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        AddSubDialog.setTitle("Adicionar Mensalista");
        AddSubDialog.setAlwaysOnTop(true);
        AddSubDialog.setMinimumSize(new java.awt.Dimension(400, 439));
        AddSubDialog.setName("AddSubDialog"); // NOI18N

        AddSubDialogName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSubDialogNameActionPerformed(evt);
            }
        });

        AddSubDialogTextName.setText("Nome");

        AddSubDialogTextLicense.setText("Placa");

        AddSubDialogTextContact.setText("Contato");

        AddSubDialogConfirmButton.setText("Adicionar");

        AddSubDialogCarModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSubDialogCarModelActionPerformed(evt);
            }
        });

        AddSubDialogTextCarModel.setText("Modelo do carro");

        AddSubDialogTextDays.setText("Dias");

        jCheckBox1.setText("jCheckBox1");

        jCheckBox2.setText("jCheckBox2");

        jCheckBox3.setText("jCheckBox3");

        jCheckBox4.setText("jCheckBox4");

        jCheckBox5.setText("jCheckBox5");

        jCheckBox6.setText("jCheckBox6");

        javax.swing.GroupLayout AddSubDialogLayout = new javax.swing.GroupLayout(AddSubDialog.getContentPane());
        AddSubDialog.getContentPane().setLayout(AddSubDialogLayout);
        AddSubDialogLayout.setHorizontalGroup(
            AddSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddSubDialogLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(AddSubDialogTextDays)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(AddSubDialogLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(AddSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddSubDialogLayout.createSequentialGroup()
                        .addComponent(jCheckBox5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(AddSubDialogConfirmButton)
                        .addGap(39, 39, 39))
                    .addGroup(AddSubDialogLayout.createSequentialGroup()
                        .addGroup(AddSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddSubDialogName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AddSubDialogLicense, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AddSubDialogContact, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AddSubDialogCarModel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(AddSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddSubDialogTextCarModel)
                            .addComponent(AddSubDialogTextContact)
                            .addComponent(AddSubDialogTextLicense)
                            .addComponent(AddSubDialogTextName))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(AddSubDialogLayout.createSequentialGroup()
                        .addGroup(AddSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AddSubDialogLayout.createSequentialGroup()
                                .addComponent(jCheckBox3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox4))
                            .addGroup(AddSubDialogLayout.createSequentialGroup()
                                .addComponent(jCheckBox1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox2)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        AddSubDialogLayout.setVerticalGroup(
            AddSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddSubDialogLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(AddSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddSubDialogName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddSubDialogTextName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddSubDialogLicense, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(AddSubDialogTextLicense))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddSubDialogContact, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddSubDialogTextContact))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddSubDialogCarModel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddSubDialogTextCarModel))
                .addGap(18, 18, 18)
                .addComponent(AddSubDialogTextDays)
                .addGap(18, 18, 18)
                .addGroup(AddSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox4))
                .addGroup(AddSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddSubDialogLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(AddSubDialogConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddSubDialogLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AddSubDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox5)
                            .addComponent(jCheckBox6))))
                .addGap(35, 35, 35))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle de Veículos");
        setAlwaysOnTop(true);
        setForeground(java.awt.Color.lightGray);
        setName("mainMenu"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        AddVeic.setText("Adicionar Veículo");
        AddVeic.setPreferredSize(new java.awt.Dimension(70, 20));
        AddVeic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddVeicActionPerformed(evt);
            }
        });

        ScrollPaneTable.setPreferredSize(new java.awt.Dimension(300, 500));

        mainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        mainTable.setMinimumSize(new java.awt.Dimension(300, 480));
        mainTable.setPreferredSize(new java.awt.Dimension(400, 500));
        mainTable.setShowGrid(true);
        ScrollPaneTable.setViewportView(mainTable);

        AddSub.setText("Adicionar Mensalista");
        AddSub.setPreferredSize(new java.awt.Dimension(70, 20));
        AddSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSubActionPerformed(evt);
            }
        });

        DesktopPane.setMinimumSize(new java.awt.Dimension(400, 439));

        javax.swing.GroupLayout DesktopPaneLayout = new javax.swing.GroupLayout(DesktopPane);
        DesktopPane.setLayout(DesktopPaneLayout);
        DesktopPaneLayout.setHorizontalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DesktopPaneLayout.setVerticalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        menubarNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menubarNew.setText("New");
        menubarNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menubarNewActionPerformed(evt);
            }
        });
        jMenu1.add(menubarNew);

        menubarOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menubarOpen.setText("Open");
        menubarOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menubarOpenActionPerformed(evt);
            }
        });
        jMenu1.add(menubarOpen);

        menubarSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menubarSave.setText("Save");
        menubarSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menubarSaveActionPerformed(evt);
            }
        });
        jMenu1.add(menubarSave);

        menubarNewWindow.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menubarNewWindow.setText("New Window");
        menubarNewWindow.setName("New Window"); // NOI18N
        menubarNewWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menubarNewWindowActionPerformed(evt);
            }
        });
        jMenu1.add(menubarNewWindow);

        MenuBar.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem5.setText("jMenuItem5");
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("jMenuItem6");
        jMenu2.add(jMenuItem6);

        MenuBar.add(jMenu2);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPaneTable, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AddVeic, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AddSub, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(DesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddVeic, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddSub, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(DesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(ScrollPaneTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddVeicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddVeicActionPerformed
        // TODO add your handling code here:
        
        AddVeicDialog.setLocation(DesktopPane.getLocationOnScreen());
        AddVeicDialog.setVisible(true);
        //AddVeicDialogConfirmButton.setFocusTraversalKeys(WIDTH, );
        
    }//GEN-LAST:event_AddVeicActionPerformed

    private void AddSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSubActionPerformed
        AddSubDialog.setLocation(DesktopPane.getLocationOnScreen());
        AddSubDialog.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_AddSubActionPerformed

    private void menubarNewWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menubarNewWindowActionPerformed
        // TODO add your handling code here:
        new Thread(){
        @Override
        public void run(){
            
            MainMenu aux = new MainMenu();
            aux.setVisible(true);
            
            }
        
        }.start();
        
        //ainda n ta 100%
        
    }//GEN-LAST:event_menubarNewWindowActionPerformed

    private void menubarOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menubarOpenActionPerformed
        // TODO add your handling code here:
        this.SaveLoadDialog.showOpenDialog(MainMenu.this);
        File file = this.SaveLoadDialog.getSelectedFile();
        String filepath = file.getAbsolutePath();
        this.list = new ArquivesManagement().LoadFile(filepath);
        
        
    }//GEN-LAST:event_menubarOpenActionPerformed

    private void menubarSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menubarSaveActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menubarSaveActionPerformed

    private void menubarNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menubarNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menubarNewActionPerformed

    private void AddVeicDialogLicenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddVeicDialogLicenseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddVeicDialogLicenseActionPerformed

    private void AddVeicDialogConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddVeicDialogConfirmButtonActionPerformed
        // TODO add your handling code here:
        VeiculeClass veic = new VeiculeClass();
        veic.setLicense(AddVeicDialogLicense.getText());
        if(AddVeicDialogManualTime.getText() == null || "".equals(AddVeicDialogManualTime.getText())){
            veic.setAutoTimeIn();
        }
        else{
            veic.setManualTimeIn(AddVeicDialogManualTime.getText());
        }
        if(AddVeicDialogSubscriber.isSelected() == true){
            veic.setManualIsSubscriber(true);
        }
        else{
            veic.setIsSubscriber(subscriberList);
        }
        if(AddVeicDialogHasKey.isSelected() == true){
            veic.setHasKey(true);
        }
        else{
            veic.setHasKey(false);
        }
        
        
        
        
        
        
        veiculeList.add(veic);
        System.out.println(veiculeList.get(0).getLicense() + " " + veiculeList.get(0).getTimeIn() + " " + veiculeList.get(0).getIsSubscriber().toString() + " " + veiculeList.get(0).getHasKey().toString() );
        
        
        
        
        
        AddVeicDialog.dispose();
        AddVeicDialogLicense.setText("");
        AddVeicDialogManualTime.setText("");
        AddVeicDialogSubscriber.setSelected(false);
        AddVeicDialogHasKey.setSelected(false);
        
        
    }//GEN-LAST:event_AddVeicDialogConfirmButtonActionPerformed

    private void AddVeicDialogManualTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddVeicDialogManualTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddVeicDialogManualTimeActionPerformed

    private void AddSubDialogNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSubDialogNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddSubDialogNameActionPerformed

    private void AddSubDialogCarModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSubDialogCarModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddSubDialogCarModelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddSub;
    private javax.swing.JDialog AddSubDialog;
    private javax.swing.JTextField AddSubDialogCarModel;
    private javax.swing.JButton AddSubDialogConfirmButton;
    private javax.swing.JTextField AddSubDialogContact;
    private javax.swing.JTextField AddSubDialogLicense;
    private javax.swing.JTextField AddSubDialogName;
    private javax.swing.JLabel AddSubDialogTextCarModel;
    private javax.swing.JLabel AddSubDialogTextContact;
    private javax.swing.JLabel AddSubDialogTextDays;
    private javax.swing.JLabel AddSubDialogTextLicense;
    private javax.swing.JLabel AddSubDialogTextName;
    private javax.swing.JButton AddVeic;
    private javax.swing.JDialog AddVeicDialog;
    private javax.swing.JToggleButton AddVeicDialogConfirmButton;
    private javax.swing.JCheckBox AddVeicDialogHasKey;
    private javax.swing.JTextField AddVeicDialogLicense;
    private javax.swing.JTextField AddVeicDialogManualTime;
    private javax.swing.JCheckBox AddVeicDialogSubscriber;
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JFileChooser SaveLoadDialog;
    private javax.swing.JScrollPane ScrollPaneTable;
    private javax.swing.JLabel TextHorarioDeEntrada;
    private javax.swing.JLabel TextPlacaDoVeiculo;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JTable mainTable;
    private javax.swing.JMenuItem menubarNew;
    private javax.swing.JMenuItem menubarNewWindow;
    private javax.swing.JMenuItem menubarOpen;
    private javax.swing.JMenuItem menubarSave;
    // End of variables declaration//GEN-END:variables
    private ArrayList<VeiculeClass> veiculeList = new ArrayList();
    private ArrayList<Subscriber> subscriberList = new ArrayList();
    private ArrayList<Object> list;


}
